### PR TITLE
Update JLD2 compat

### PR DESCRIPTION
**Pull request by filchristou**

### CODE REVIEW

**Comment by gdalle** [comment]
Thanks! Any idea why CompatHelper didn't warn us?

**Comment by filchristou** [comment]
Is it even enabled ? I don't see any compat-helper PRs. So I take it I can merge.

**Comment by gdalle** [comment]
Maybe we could drop the old versions in the process? I don't know exactly whether the breaking changes in [JLD2 v0.5.0](https://github.com/JuliaIO/JLD2.jl/releases/tag/v0.5.0) affect us here, never really looked into the encoding

**Comment by filchristou** [comment]
I wouldn't do that. Maybe some people are still use older julia versions or have some JLD2 v0.4 formats laying around.

**Review by gdalle — APPROVED** [review]

**Pull request merged**
